version: '3.7'

services:
  grasscutter:
    image: grasscutter
    container_name: grasscutter2
    build: ./
    depends_on:
      - mongodb_grasscutter
    restart: unless-stopped

  mongodb_grasscutter:
    container_name: mongodb_grasscutter2
    image: mongo
    restart: unless-stopped
